services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_projet_ctr
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      # Running without auth for local dev speed. 
      # Set MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD for prod.
      MONGO_INITDB_DATABASE: projet_ctr_delivery

volumes:
  mongodb_data:
    driver: local
