# Generated by Django 4.2.29 on 2026-04-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0004_designlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(blank=True, max_length=24)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_address', models.TextField(blank=True)),
                ('fabric_requested', models.CharField(max_length=255)),
                ('fabric_id', models.IntegerField(blank=True, null=True)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_production', 'En production'), ('completed', 'Terminé'), ('shipped', 'Expédié')], default='pending', max_length=20)),
                ('fabric_status', models.CharField(choices=[('available', 'Stock disponible'), ('to_order', 'À commander'), ('ordered', 'Commandé'), ('received', 'Reçu')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couture_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='couturehouse.couturehouseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LocalFabricStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couture_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_fabrics', to='couturehouse.couturehouseprofile')),
            ],
        ),
    ]
