# Generated by Django 4.2.29 on 2026-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0005_order_localfabricstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturehouseprofile',
            name='portfolio_photos_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='couturehouseprofile',
            name='workshop_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
