# Generated by Django 4.2.29 on 2026-04-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0006_couturehouseprofile_portfolio_photos_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturehouseprofile',
            name='professional_license_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
