# Generated by Django 4.2.29 on 2026-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0007_couturehouseprofile_professional_license_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couturehouseprofile',
            name='commercial_register_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='couturehouseprofile',
            name='id_card_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='couturehouseprofile',
            name='portfolio_photos_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='couturehouseprofile',
            name='professional_license_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='couturehouseprofile',
            name='workshop_photo_url',
            field=models.TextField(blank=True),
        ),
    ]
