# Generated by Django 4.2.29 on 2026-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0009_order_is_paid_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturehouseprofile',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couturehouseprofile',
            name='introduction_video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
