# Generated by Django 4.2.29 on 2026-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0010_couturehouseprofile_about_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couturehouseprofile',
            name='introduction_video_url',
        ),
        migrations.AddField(
            model_name='couturehouseprofile',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='atelier_videos/'),
        ),
    ]
