# Generated by Django 4.2.29 on 2026-04-05 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couturehouse', '0011_remove_couturehouseprofile_introduction_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturehouseprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='couturehouseprofile',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AtelierReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_atelier_reviews', to=settings.AUTH_USER_MODEL)),
                ('couture_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='couturehouse.couturehouseprofile')),
            ],
            options={
                'unique_together': {('couture_house', 'client_user')},
            },
        ),
    ]
