# Generated by Django 4.2.29 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0012_couturehouseprofile_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturehouseprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
