# Generated by Django 4.2.29 on 2026-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0013_couturehouseprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='design_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
