# Generated by Django 4.2.29 on 2026-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0014_order_components_order_design_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
