# Generated by Django 4.2.28 on 2026-02-22 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('nomOrganization', models.CharField(blank=True, max_length=200)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('typeProduct', models.CharField(blank=True, max_length=200)),
                ('specialites', models.TextField(blank=True)),
                ('numeroLicence', models.CharField(blank=True, max_length=100)),
                ('siteWeb', models.URLField(blank=True)),
                ('nombreEmployes', models.CharField(blank=True, max_length=50)),
                ('anneeCreation', models.CharField(blank=True, max_length=4)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('codePostal', models.CharField(blank=True, max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('nomContact', models.CharField(blank=True, max_length=100)),
                ('prenomContact', models.CharField(blank=True, max_length=100)),
                ('telephoneContact', models.CharField(blank=True, max_length=50)),
                ('certificationsQualite', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fabrics/')),
                ('color', models.JSONField(blank=True, default=list)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materiel', models.CharField(blank=True, max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
