# Generated by Django 4.2.29 on 2026-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0003_supplierprofile_commercial_register_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='fabric_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='min_price_per_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
