# Generated by Django 4.2.29 on 2026-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0004_supplierprofile_fabric_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
