# Generated by Django 4.2.29 on 2026-03-31 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournisseur', '0005_fabric_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_liked_by', to='fournisseur.fabric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fabric')},
            },
        ),
    ]
