# Generated by Django 4.2.29 on 2026-04-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0006_fabriclike'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couture_house_id', models.IntegerField()),
                ('couture_house_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard'), ('rapide', 'Rapide'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('delivery_preference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fournisseur.fabric')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='fournisseur.supplierprofile')),
            ],
        ),
    ]
