# Generated by Django 4.2.29 on 2026-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0007_fabricorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='fabric_quality_cert_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='fabric_sample_photos_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='warehouse_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
