# Generated by Django 4.2.29 on 2026-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0008_supplierprofile_fabric_quality_cert_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='commercial_register_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='fabric_quality_cert_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='fabric_sample_photos_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='id_card_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='warehouse_photo_url',
            field=models.TextField(blank=True),
        ),
    ]
