# Generated by Django 4.2.29 on 2026-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0009_alter_supplierprofile_commercial_register_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('preparing', 'En préparation'), ('ready_for_pickup', 'Prêt pour enlèvement'), ('shipped', 'Expédié'), ('in_transit', 'En cours de livraison'), ('delivered', 'Livré'), ('received', 'Réceptionné'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
