# Generated by Django 4.2.29 on 2026-04-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournisseur', '0010_alter_fabricorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jewelry/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('quantite', models.IntegerField(default=0)),
                ('materiel', models.CharField(blank=True, max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
