# Generated by Django 4.2.29 on 2026-04-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0011_jewelry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_jewelry', to='fournisseur.fabric'),
        ),
    ]
