# Generated by Django 4.2.29 on 2026-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0012_jewelry_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='supplier_videos/'),
        ),
    ]
