# Generated by Django 4.2.29 on 2026-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0013_supplierprofile_introduction_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='color_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
