# Generated by Django 4.2.29 on 2026-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0014_fabric_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricorder',
            name='carrier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricorder',
            name='route_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
