# Generated by Django 4.2.29 on 2026-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_carrier_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='commercial_register_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='carrier',
            name='id_card_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
