# Generated by Django 4.2.29 on 2026-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_carrier_commercial_register_url_carrier_id_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='delivery_time_guarantee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carrier',
            name='insurance_coverage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carrier',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
