# Generated by Django 4.2.29 on 2026-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_shipmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
