# Generated by Django 4.2.29 on 2026-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_route_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='carrier',
            name='review_count',
            field=models.IntegerField(default=12),
        ),
    ]
