# Generated by Django 4.2.29 on 2026-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_carrier_rating_carrier_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='insurance_document_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='carrier',
            name='luxury_reference_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='carrier',
            name='vehicle_photos_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
