# Generated by Django 4.2.29 on 2026-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_carrier_insurance_document_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='commercial_register_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id_card_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='insurance_document_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='luxury_reference_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='vehicle_photos_url',
            field=models.TextField(blank=True),
        ),
    ]
