# Generated by Django 4.2.29 on 2026-04-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couturehouse', '0012_couturehouseprofile_rating_and_more'),
        ('delivery', '0009_alter_carrier_commercial_register_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='delivery.carrier')),
                ('couture_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_carrier_reviews', to='couturehouse.couturehouseprofile')),
            ],
            options={
                'unique_together': {('carrier', 'couture_house')},
            },
        ),
    ]
