# Generated by Django 4.2.29 on 2026-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_carrierreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to='carrier_videos/'),
        ),
    ]
