# Generated by Django 4.2.29 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_carrier_introduction_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
