# Generated by Django 4.2.29 on 2026-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_carrier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentrequest',
            name='client_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
