# Generated by Django 4.2.29 on 2026-04-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_info_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('couture_house', 'Couture House'), ('fournisseur', 'Fournisseur'), ('delivery', 'Delivery'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
