import json
import logging
import os
from pathlib import Path
from typing import Any

from django.conf import settings
from django.http import JsonResponse, FileResponse, HttpRequest, HttpResponseNotFound
from django.views.decorators.csrf import csrf_exempt

import importlib
body_processor_mod = importlib.import_module("3d_model_body_measurements.body_processor")
BodyProcessor = body_processor_mod.BodyProcessor


logger = logging.getLogger(__name__)


PIPELINE_ROOT = Path(getattr(settings, "PIPELINE_ROOT", Path(__file__).resolve().parent.parent / "3d_model_body_measurements"))
UPLOAD_FOLDER = Path(getattr(settings, "PIPELINE_UPLOADS", PIPELINE_ROOT / "uploads"))
RESULTS_FOLDER = Path(getattr(settings, "PIPELINE_RESULTS", PIPELINE_ROOT / "results"))

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(RESULTS_FOLDER, exist_ok=True)

processor = BodyProcessor()


def _parse_float(value: str | None, default: float) -> float:
    try:
        return float(value) if value is not None else default
    except (TypeError, ValueError):
        return default


def _parse_int(value: str | None) -> int | None:
    try:
        return int(value) if value and value.isdigit() else None
    except (TypeError, ValueError):
        return None


@csrf_exempt
def process_video(request: HttpRequest):
    """
    Django equivalent of the old Flask /process endpoint.
    Accepts multipart/form-data with a video file and user metadata.
    """
    if request.method != "POST":
        return JsonResponse({"error": "Method not allowed"}, status=405)

    video = request.FILES.get("video")
    if not video or not getattr(video, "name", ""):
        return JsonResponse({"error": "No video provided"}, status=400)

    # Form data
    height = _parse_float(request.POST.get("height"), 175.0)
    weight = _parse_float(request.POST.get("weight"), 70.0)
    age = _parse_int(request.POST.get("age"))
    gender = request.POST.get("gender", "men")
    cut_preference: str | None = request.POST.get("cut_preference") or None

    quality = (request.POST.get("quality") or "balanced").lower()
    if quality not in ("fast", "balanced", "high"):
        quality = "balanced"

    save_path = UPLOAD_FOLDER / video.name
    with open(save_path, "wb+") as dest:
        for chunk in video.chunks():
            dest.write(chunk)

    logger.info(
        "Processing video: %s for %scm, %skg, age=%s, gender=%s",
        video.name,
        height,
        weight,
        age,
        gender,
    )

    try:
        result: dict[str, Any] = processor.process(
            str(save_path),
            str(RESULTS_FOLDER),
            height_cm=height,
            weight_kg=weight,
            age=age,
            gender=gender,
            cut_preference=cut_preference,
            quality=quality,
        )

        # The pipeline already writes result.json and builds mesh/plots;
        # just return the dict as JSON.
        if result.get("status") == "error":
            result.setdefault("plots", {})
        else:
            # Plots are generated by PlotGenerator in the original Flask app;
            # here we keep the contract and let the processor or caller handle extras.
            result.setdefault("plots", {})

        return JsonResponse(result)
    except Exception as exc:  # noqa: BLE001
        logger.exception("Error processing video: %s", exc)
        return JsonResponse({"error": str(exc)}, status=500)


def _result_path(run_id: str) -> Path:
    return RESULTS_FOLDER / run_id / "result.json"


def serve_results(request: HttpRequest, filepath: str):
    """
    Serve result files (meshes, images, JSON, etc.).
    Mirrors the behavior of the Flask /results/<path> route.
    """
    full_path = RESULTS_FOLDER / filepath

    if full_path.is_dir():
        result_json = full_path / "result.json"
        if result_json.exists():
            with open(result_json, "r", encoding="utf-8") as f:
                data = json.load(f)
            return JsonResponse(data)
        return JsonResponse({"error": "Result not found"}, status=404)

    if full_path.exists():
        content_type = "model/gltf-binary" if full_path.suffix == ".glb" else "application/octet-stream"
        response = FileResponse(open(full_path, "rb"), content_type=content_type)
        response["Access-Control-Allow-Origin"] = "*"
        return response

    logger.warning("File not found: %s", full_path)
    return JsonResponse({"error": "File not found"}, status=404)


def get_measurements(_request: HttpRequest, run_id: str):
    """Return measurements for a given run_id."""
    path = _result_path(run_id)
    if not path.exists():
        return JsonResponse({"error": "Result not found"}, status=404)

    with open(path, "r", encoding="utf-8") as f:
        result = json.load(f)

    return JsonResponse(result.get("measurements", {}))


def get_recommendations(_request: HttpRequest, run_id: str):
    """Return fashion recommendations for a given run_id."""
    path = _result_path(run_id)
    if not path.exists():
        return JsonResponse({"error": "Result not found"}, status=404)

    with open(path, "r", encoding="utf-8") as f:
        result = json.load(f)

    return JsonResponse(result.get("fashion_recommendations", {}))


@csrf_exempt
def correct_measurements(request: HttpRequest, run_id: str):
    """
    Correct measurements based on user input.
    JSON body:
        - measurement_key
        - new_value (cm)
    """
    if request.method != "POST":
        return JsonResponse({"error": "Method not allowed"}, status=405)

    path = _result_path(run_id)
    if not path.exists():
        return JsonResponse({"error": "Result not found"}, status=404)

    try:
        payload = json.loads(request.body.decode("utf-8") or "{}")
    except json.JSONDecodeError:
        return JsonResponse({"error": "Invalid JSON body"}, status=400)

    if "measurement_key" not in payload or "new_value" not in payload:
        return JsonResponse({"error": "Invalid correction data"}, status=400)

    with open(path, "r", encoding="utf-8") as f:
        result = json.load(f)

    measurement_key = payload["measurement_key"]
    try:
        new_value = float(payload["new_value"])
    except (TypeError, ValueError):
        return JsonResponse({"error": "Invalid new_value"}, status=400)

    for category in ["basics", "heights", "widths", "functional"]:
        if category not in result.get("measurements", {}):
            continue
        for m in result["measurements"][category]:
            if m.get("key") == measurement_key:
                m["value_cm"] = new_value
                m["value"] = f"{new_value:.1f}"
                m["corrected"] = True
                m["confidence"] = 1.0

    with open(path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    return JsonResponse({"success": True, "result": result})


def health(_request: HttpRequest):
    """Django version of the Flask /health endpoint."""
    morphology_enabled = getattr(processor, "morphology_enabled", True)
    fashion_enabled = getattr(processor, "fashion_enabled", True)
    return JsonResponse(
        {
            "status": "healthy",
            "version": "2.0-django",
            "modules": {
                "processor": True,
                "morphology": bool(morphology_enabled),
                "fashion": bool(fashion_enabled),
            },
        }
    )

